[package]
name = "wasm_test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.92"

[dev-dependencies]
wasm-bindgen-cli = "0.2.92"

[profile.release]
opt-level = 's'
strip = "debuginfo"
lto = true